# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-26 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('full_name_kana', models.CharField(max_length=64)),
                ('first_name_kana', models.CharField(max_length=32)),
                ('last_name_kana', models.CharField(max_length=32)),
                ('sex', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1)),
                ('birth_date', models.DateField()),
                ('age', models.CharField(max_length=3)),
                ('zip_code', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=128)),
                ('address2', models.CharField(max_length=128)),
                ('address_kana', models.CharField(max_length=128)),
                ('address2_kana', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=32)),
                ('cellphone_number', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('acquired_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.BasicInfo')),
                ('certification', models.ManyToManyField(to='cv.Certification')),
            ],
        ),
        migrations.CreateModel(
            name='CVTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.BasicInfo')),
                ('certification', models.ManyToManyField(to='cv.Certification')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('e', '入学'), ('g', '卒業'), ('d', '中途退学'), ('t', '編入'), ('m', '転入'), ('l', '休学')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commuting_time', models.CharField(max_length=12)),
                ('dependent', models.IntegerField()),
                ('spouse', models.CharField(choices=[('y', '有'), ('n', '無')], max_length=1)),
                ('duty_of_support', models.CharField(choices=[('y', '有'), ('n', '無')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('e', '入社'), ('q', '退社')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='education',
            field=models.ManyToManyField(to='cv.Education'),
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='work_experience',
            field=models.ManyToManyField(to='cv.WorkExperience'),
        ),
        migrations.AddField(
            model_name='cv',
            name='education',
            field=models.ManyToManyField(to='cv.Education'),
        ),
        migrations.AddField(
            model_name='cv',
            name='extra_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.ExtraInfo'),
        ),
        migrations.AddField(
            model_name='cv',
            name='qustion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Question'),
        ),
        migrations.AddField(
            model_name='cv',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Reason'),
        ),
        migrations.AddField(
            model_name='cv',
            name='work_experience',
            field=models.ManyToManyField(to='cv.WorkExperience'),
        ),
    ]
